services:
  crai-jaf-backend:
    build:
      context: .
      target: production
    image: crai-jaf-backend
    container_name: crai-jaf-backend
    depends_on:
      - crai-jaf-backend-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: crai-jaf-backend-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AZURE_OPENAI_INSTANCE_NAME: ${AZURE_OPENAI_INSTANCE_NAME:-test}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY:-test}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-test}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME:-test}
      POSTGRES_DB: crai-jaf
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
      POSTGRES_HOST: 'host.docker.internal'
      POSTGRES_PORT: 5432

  crai-jaf-backend-postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    image: crai-jaf-backend-postgres
    environment:
      POSTGRES_DB: crai-jaf
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres

  