# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  crai-jaf-backend:
    build:
      target: development
    image: crai-jaf-backend-development
    container_name: crai-jaf-backend-development
    ports:
      - "3001:3000"
      - "9230:9229"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json
      
  crai-jaf-backend-postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: